name: Deploy to GitHub Pages
on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2

      - name: Node istallation and build

        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm i
      - run: npm run build

      - name: Deploy to GitHub Pages
        uses: jamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages
          folder: dist
